
const prendas = [
  {
    tipo: "Remera",
    estilo: "Manga corta",
    talle: "M",
    precio: 300,
    color: "Blanco",
    material: "Algodón",
  },
  {
    tipo: "Pantalon",
    estilo: "Jeans",
    talle: "L",
    precio: 400,
    color: "Negro",
    material: "Jean",
  },
  {
    tipo: "Short",
    estilo: "Deportivo",
    talle: "S",
    precio: 200,
    color: "Azul",
    material: "Poliéster",
  },
  {
    tipo: "Buzo",
    estilo: "Cierre frontal",
    talle: "M",
    precio: 500,
    color: "Gris",
    material: "Algodón",
  },
  {
    tipo: "Campera",
    estilo: "Invierno",
    talle: "L",
    precio: 800,
    color: "Negro",
    material: "Cuero",
  },
  {
    tipo: "Medias",
    estilo: "Deportivas",
    talle: "Único",
    precio: 25,
    color: "Blanco",
    material: "Algodón",
  },
  {
    tipo: "Calzones",
    estilo: "Boxer",
    talle: "M",
    precio: 15,
    color: "Rojo",
    material: "Algodón",
  },
  {
    tipo: "Camisa",
    estilo: "Casual",
    talle: "L",
    precio: 350,
    color: "Azul",
    material: "Lino",
  },
  {
    tipo: "Remera",
    estilo: "Manga larga",
    talle: "L",
    precio: 350,
    color: "Negro",
    material: "Algodón",
  },
  {
    tipo: "Pantalon",
    estilo: "Casual",
    talle: "M",
    precio: 700,
    color: "Verde",
    material: "Gabardina",
  },
  {
    tipo: "Short",
    estilo: "Playa",
    talle: "S",
    precio: 150,
    color: "Amarillo",
    material: "Algodón",
  },
  {
    tipo: "Buzo",
    estilo: "Capucha",
    talle: "L",
    precio: 600,
    color: "Azul",
    material: "Algodón",
  },
  {
    tipo: "Campera",
    estilo: "Cuero",
    talle: "M",
    precio: 1000,
    color: "Marrón",
    material: "Jean",
  },
  {
    tipo: "Medias",
    estilo: "Casuales",
    talle: "Único",
    precio: 20,
    color: "Gris",
    material: "Algodón",
  },
  {
    tipo: "Calzones",
    estilo: "Boxer",
    talle: "L",
    precio: 18,
    color: "Azul",
    material: "Algodón",
  },
  {
    tipo: "Camisa",
    estilo: "Formal",
    talle: "S",
    precio: 500,
    color: "Blanco",
    material: "Algodón",
  },
  {
    tipo: "Remera",
    estilo: "Sin mangas",
    talle: "S",
    precio: 250,
    color: "Amarillo",
    material: "Algodón",
  },
  {
    tipo: "Pantalon",
    estilo: "Deportivo",
    talle: "L",
    precio: 300,
    color: "Negro",
    material: "Poliéster",
  },
  {
    tipo: "Short",
    estilo: "Casual",
    talle: "M",
    precio: 120,
    color: "Gris",
    material: "Jean",
  },
  {
    tipo: "Buzo",
    estilo: "Estampado",
    talle: "S",
    precio: 450,
    color: "Rojo",
    material: "Algodón",
  },
  {
    tipo: "Campera",
    estilo: "Deportiva",
    talle: "L",
    precio: 700,
    color: "Negro",
    material: "Poliéster",
  },
  {
    tipo: "Medias",
    estilo: "Rayadas",
    talle: "Único",
    precio: 30,
    color: "Azul",
    material: "Algodón",
  },
  {
    tipo: "Calzones",
    estilo: "Boxer",
    talle: "S",
    precio: 12,
    color: "Verde",
    material: "Algodón",
  },
  {
    tipo: "Camisa",
    estilo: "Casual",
    talle: "M",
    precio: 400,
    color: "Gris",
    material: "Algodón",
  }
]
